express-notes-api - Frank Bishop
FrankBishop/c0121-code-solutions pull request #101
Opened 2021-03-18 00:49 UTC by FrankBishop

Somehow the previous pull request, https://github.com/FrankBishop/c0121-code-solutions/pull/94, got merged at the same time I merged another pull request.  I put in the requested fixes, let me know if there is anymore feedback on this, thanks.

2021-03-18 17:19 UTC, thebearingedge requested changes

2021-03-18 17:19 UTC, thebearingedge commented on express-notes-api/index.js
> +    res.status(201).json(req.body);
We don't want to respond before writing the file. For example, if there is an error writing the file, we won't be able to send the `500` error, because we already sent the `201` success.

2021-03-18 17:19 UTC, thebearingedge commented on express-notes-api/index.js
>          });
The success response should go in the callback. We don't know if we should respond with a `204` or `500` until this callback runs.

2021-03-18 17:19 UTC, thebearingedge commented on express-notes-api/index.js
> +        });
The success response should go in the callback. We don't know if we should respond with a `204` or `500` until this callback runs.

2021-03-19 01:03 UTC, FrankBishop commented
Thanks, I made the fixes and pushed them

2021-03-19 01:19 UTC, thebearingedge approved these changes

2021-03-19 01:20 UTC, merged