Sgt back end - Frank Bishop
FrankBishop/c0121-code-solutions pull request #105
Opened 2021-03-21 19:57 UTC by FrankBishop

2021-03-22 20:32 UTC, thebearingedge requested changes
Great job, just one small change.

2021-03-22 20:32 UTC, thebearingedge commented on sgt-back-end/index.js
> +  }
Rather than use a loop, which relies on key order, just create your array explicitly.
```js
const params = [req.body.course, req.body.name, req.body.score, gradeId];
```

2021-03-23 23:53 UTC, FrankBishop commented
I made the change and pushed it, thank you

2021-03-23 23:54 UTC, thebearingedge approved these changes

2021-03-24 00:35 UTC, merged