array-reduce - Frank Bishop
FrankBishop/c0121-code-solutions pull request #108
Opened 2021-03-22 23:01 UTC by FrankBishop

![Screenshot (349)](https://user-images.githubusercontent.com/75149451/112068774-d9dc2200-8b27-11eb-85aa-b48736d48e30.png)

2021-03-22 23:22 UTC, thebearingedge requested changes

2021-03-22 23:22 UTC, thebearingedge commented on array-reduce/main.js
> +  accumulator += 0;
You should be able to remove line 25

2021-03-23 00:22 UTC, FrankBishop commented
Hi, I pushed the fix

2021-03-23 16:19 UTC, thebearingedge approved these changes

2021-03-23 16:59 UTC, merged