api-registration - Frank Bishop
FrankBishop/c0121-code-solutions pull request #130
Opened 2021-03-30 23:52 UTC by FrankBishop

![Screenshot (414)](https://user-images.githubusercontent.com/75149451/113070804-4bdfe700-9178-11eb-9ec9-378024b158a9.png)

2021-03-30 23:58 UTC, thebearingedge requested changes

2021-03-30 23:58 UTC, thebearingedge commented on api-registration/server/index.js
> +        });
You can pass the `err` to `next()` here instead of all of this.

2021-03-30 23:58 UTC, thebearingedge commented on api-registration/server/index.js
> +    });
You can pass the `err` to `next()` here.

2021-03-31 00:01 UTC, FrankBishop commented
Thanks, that makes it a lot cleaner, I got it fixed and pushed it

2021-03-31 00:02 UTC, thebearingedge requested changes

2021-03-31 00:02 UTC, thebearingedge commented on api-registration/server/index.js
> +          const userAccount = result.rows[0];
Sorry, I missed this part. The client should not receive the hashed password in the response.

2021-03-31 00:07 UTC, FrankBishop commented
I got that fixed and pushed also, thanks

2021-03-31 00:11 UTC, thebearingedge approved these changes

2021-03-31 00:11 UTC, merged