React accordion component - Frank Bishop
FrankBishop/c0121-code-solutions pull request #136
Opened 2021-04-27 02:05 UTC by FrankBishop

![accord](https://user-images.githubusercontent.com/75149451/116173916-47004b80-a6c2-11eb-9fc6-5126efdfa39e.gif)

2021-04-28 02:54 UTC, thebearingedge requested changes

2021-04-28 02:54 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +    let accordNumber = event.target.parentElement.getAttribute('number');
We don't traverse the DOM like this in react. Why not add the event listener to the parent element in the first place?

2021-04-28 02:54 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +        <h2 onClick={this.handleClick} onDoubleClick={this.close}>{language.language}</h2>
Instead of closing on double-click, it should close even if the user waits 2 days to click the same one again 😂 . You can add some conditional logic in your event listener. If the state currently holds the same language that gets clicked, set the state back to `null`.

2021-04-28 03:08 UTC, FrankBishop commented
Thanks, I was able to make the changes, except I wasn't able to add the event listener to the parent element of H2.  When I tried that, I had to click to the right of the H2 for it to recognize the parent DIV as the target.  What I did was move the attribute I needed down to the H2 element.

2021-04-28 03:29 UTC, thebearingedge requested changes
> Thanks, I was able to make the changes, except I wasn't able to add the event listener to the parent element of H2. When I tried that, I had to click to the right of the H2 for it to recognize the parent DIV as the target. What I did was move the attribute I needed down to the H2 element.

I don't really understand what you mean. The user should be able to click anywhere on the div that contains the h2, including the h2. The h2 should be the full width of the div. I think part of the problem is that you made the paragraph and h2 30% of their parent's width, instead of just making the parent less wide.

2021-04-28 03:39 UTC, FrankBishop commented
I made the div take up less space, so the h2 would be the same width as the div.  The console.logs show that it still makes the h2 the event.target instead of the div.

![event target](https://user-images.githubusercontent.com/75149451/116342975-5fdb3080-a798-11eb-8448-f9f5cabe0299.gif)

2021-04-28 19:26 UTC, thebearingedge requested changes
Ok, so to complete this, you can pass an arrow function to each `<div>` and modify your click handler to accept a `language.number` instead of an `event`

```jsx
<div onClick={() => this.handleClick(language.number)} key={language.number}>
```

```js
handleClick(number) {
  // logic here to update state based on the number passed in
}
```

2021-04-28 20:29 UTC, FrankBishop commented
Thank you, that fixed it, I pushed the changes.

2021-05-03 23:13 UTC, thebearingedge approved these changes

2021-05-06 18:44 UTC, merged