React carousel component - Frank Bishop
FrankBishop/c0121-code-solutions pull request #137
Opened 2021-04-27 23:28 UTC by FrankBishop

![carousel3](https://user-images.githubusercontent.com/75149451/116324716-76bc5b80-a775-11eb-8058-0e92b828dd85.gif)

2021-04-28 02:56 UTC, thebearingedge requested changes

2021-04-28 02:56 UTC, thebearingedge commented on react-carousel-component/src/carousel.jsx
> +    );
The circles should be filled based on the currently active index.

2021-04-28 03:26 UTC, FrankBishop commented
Thanks, I made the fixes and pushed them.

2021-05-06 16:13 UTC, thebearingedge approved these changes

2021-05-06 18:45 UTC, merged