CSS-Brochure - Frank Bishop
FrankBishop/c0121-code-solutions pull request #16
Opened 2021-01-21 04:57 UTC by FrankBishop

![Screenshot (31)](https://user-images.githubusercontent.com/75149451/105281939-0b556300-5b62-11eb-988d-2dd9d7e6e33f.png)

2021-01-21 21:04 UTC, codingcodymiller requested changes
Hey Frank! Great job so far, please see my notes. I have recommended a few changes, and then we can adjust from there.

2021-01-21 21:04 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +}
You probably don't meant to text align everything.

2021-01-21 21:04 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  width: 20%;
You should stick to `px` for widths as much as possible.

2021-01-21 21:04 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  width: 4%;
You should stick to `px` for widths as much as possible.

2021-01-21 21:04 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  width: 20%;
You should stick to `px` for widths as much as possible.

2021-01-21 23:07 UTC, FrankBishop commented
Thanks for the feedback, here is an updated version that implemented the feedback.

![Screenshot (45)](https://user-images.githubusercontent.com/75149451/105423475-6cc91080-5bfa-11eb-9cec-7e4cf1272c79.png)

2021-01-23 00:19 UTC, codingcodymiller approved these changes
🥳 🥳 🥳

2021-01-23 00:27 UTC, merged