CSS-Grid-Classes - Frank Bishop
FrankBishop/c0121-code-solutions pull request #18
Opened 2021-01-21 21:05 UTC by FrankBishop

![Screenshot (43)](https://user-images.githubusercontent.com/75149451/105412285-5f575a80-5be9-11eb-8127-842f66dcacec.png)
![Screenshot (42)](https://user-images.githubusercontent.com/75149451/105412297-62524b00-5be9-11eb-8ecd-3b4edb299862.png)

2021-01-21 22:50 UTC, codingcodymiller requested changes
Hey Frank, great code so far! Please see my notes

2021-01-21 22:50 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +.column-1 {
This should be name something like `column-third`

2021-01-21 22:50 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +.column-2 {
This should be name something like `column-fourth`

2021-01-21 22:50 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +  flex-wrap: wrap;
This can be removed

2021-01-21 22:50 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +  flex-wrap: wrap;
This can be removed

2021-01-21 22:50 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +.text-1 {
This should be named something like `column-third`

2021-01-21 22:50 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +.text-2 {
This should be named something like `column-two-thirds`

2021-01-21 23:21 UTC, FrankBishop commented
Hi, thanks for the feedback, I have implemented it.  Here is the updated code.
![Screenshot (48)](https://user-images.githubusercontent.com/75149451/105424462-4a37f700-5bfc-11eb-92e0-47701e4b6428.png)
![Screenshot (49)](https://user-images.githubusercontent.com/75149451/105424474-4d32e780-5bfc-11eb-97c2-3fdd29879325.png)

2021-01-22 20:47 UTC, codingcodymiller approved these changes
Nicely done!! 👍

2021-01-22 23:48 UTC, merged