Css three column layout - Frank Bishop
FrankBishop/c0121-code-solutions pull request #19
Opened 2021-01-22 03:31 UTC by FrankBishop

![Screenshot (51)](https://user-images.githubusercontent.com/75149451/105442747-2639dd00-5c1f-11eb-8348-d20586f00db8.png)

2021-01-23 02:58 UTC, codingcodymiller requested changes
Nice work so far! A couple changes:

2021-01-23 02:58 UTC, codingcodymiller commented on css-three-column-layout/index.html
> +    </div>
This can be removed.

2021-01-23 02:58 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
This can be removed.

2021-01-23 02:58 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
This can be removed.

2021-01-23 02:58 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  flex-basis: 22%;
This will compete with the above `width` declaration in this rule. Determine which one you want, and remove the other

2021-01-23 18:49 UTC, FrankBishop commented
Hi, thanks for the feedback, I implemented the requested changes.

![Screenshot (70)](https://user-images.githubusercontent.com/75149451/105611187-9dc75380-5d68-11eb-9b51-9bb4ded5abf6.png)

2021-01-26 23:22 UTC, codingcodymiller approved these changes
Nice work!! 👏

2021-01-26 23:22 UTC, merged