css-positioning - Frank Bishop
FrankBishop/c0121-code-solutions pull request #20
Opened 2021-01-22 19:01 UTC by FrankBishop

![Screenshot (62)](https://user-images.githubusercontent.com/75149451/105533433-fcc19580-5ca0-11eb-87b9-51f0fdf59e9b.png)
![Screenshot (63)](https://user-images.githubusercontent.com/75149451/105533468-09de8480-5ca1-11eb-81e2-44978cdf4ec6.png)
![Screenshot (64)](https://user-images.githubusercontent.com/75149451/105533519-19f66400-5ca1-11eb-90ad-de938481fbf0.png)

2021-01-22 21:16 UTC, codingcodymiller requested changes
Hey Frank, great job so far! Please see my notes:

2021-01-22 21:16 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  left: 225px;
Please revise this to use smaller measurements from `right` as we discussed in Q&A

2021-01-22 21:16 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  position: relative;
This should be `absolute`. Make sure you check your output again after making the change, there may be revisions needed.

2021-01-22 21:16 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  position: relative;
This should be `absolute`. Make sure you check your output again after making the change, there may be revisions needed.

2021-01-22 21:16 UTC, codingcodymiller commented on css-positioning/fixed.css
> +  left: 37%;
Rather than this manual movement, try making this element the full width of the viewport. It already has `text-align: center` applies, which will handle centering the text.

2021-01-22 21:16 UTC, codingcodymiller commented on css-positioning/relative.css
> +}
Rather than repeat `position: relative` for each rule here, you can apply it in the `.pokemon > img` rule above, and only need to apply it once.

2021-01-23 00:02 UTC, FrankBishop commented
Hi, thanks for the feedback, I implemented the requested fixes.
![Screenshot (67)](https://user-images.githubusercontent.com/75149451/105561272-2099d100-5ccb-11eb-99f6-043687eb0c15.png)
![Screenshot (68)](https://user-images.githubusercontent.com/75149451/105561278-242d5800-5ccb-11eb-9baf-42a9ff5e823d.png)
![Screenshot (69)](https://user-images.githubusercontent.com/75149451/105561282-27284880-5ccb-11eb-8876-21765ce0cf0a.png)

2021-01-23 01:06 UTC, codingcodymiller approved these changes
Nice work!!!

2021-01-23 18:34 UTC, merged