Css two column layout - Frank Bishop
FrankBishop/c0121-code-solutions pull request #21
Opened 2021-01-22 23:47 UTC by FrankBishop

![Screenshot (66)](https://user-images.githubusercontent.com/75149451/105560605-1a0a5a00-5cc9-11eb-80e6-fe80c275d549.png)

2021-01-23 03:12 UTC, codingcodymiller requested changes
Great work so far! Please see my notes:

2021-01-23 03:12 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-left: 425px;
😱 😱 😱 😱 😱 

Margin should not be used to reposition elements. If you want to center the button, it can be done by applying `text-align: center`

2021-01-23 03:12 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-left: 100px;
This also seems excessive, try to find a different way to do this than margin and padding

2021-01-23 19:12 UTC, FrankBishop commented on css-two-column-layout/styles.css
> +  margin-left: 425px;
I was able to remove the left-margin by applying text-align: center, but I still needed the top margin.

2021-01-23 19:42 UTC, FrankBishop commented on css-two-column-layout/styles.css
> +  margin-left: 100px;
I got creative and wrapped each row within each column in a div to get this to work.

2021-01-23 19:44 UTC, FrankBishop commented
Hi,

Thanks for the feedback.  Here is my updated version.
![Screenshot (72)](https://user-images.githubusercontent.com/75149451/105612321-2990ae00-5d70-11eb-8c40-15cafb6503b0.png)

2021-01-27 02:38 UTC, codingcodymiller approved these changes
Nice work!!

2021-01-27 03:31 UTC, merged