javascript-constructors - Frank Bishop
FrankBishop/c0121-code-solutions pull request #62
Opened 2021-02-16 21:17 UTC by FrankBishop

![Screenshot (205)](https://user-images.githubusercontent.com/75149451/108122542-4f506080-7059-11eb-98de-051c56f314ec.png)

2021-02-16 21:19 UTC, codingcodymiller requested changes
Hey Frank! You seem to have missed the `new-objects.js` portion of the exercise, please complete it and update your pull request 
![108121538-cab11280-7057-11eb-9e65-d8402ea33610](https://user-images.githubusercontent.com/32880187/108122722-963e5600-7059-11eb-82b6-be5f8e3a562b.png)

2021-02-16 21:23 UTC, FrankBishop commented
Oh, sorry, I did that part but forgot to put in the screenshots.
![Screenshot (201)](https://user-images.githubusercontent.com/75149451/108122973-fb924700-7059-11eb-8915-7f26cc5ae753.png)
![Screenshot (202)](https://user-images.githubusercontent.com/75149451/108122984-01882800-705a-11eb-824b-1b40471d85ab.png)
![Screenshot (203)](https://user-images.githubusercontent.com/75149451/108122996-08169f80-705a-11eb-9c26-37a7a2fc99aa.png)
![Screenshot (204)](https://user-images.githubusercontent.com/75149451/108123009-0b119000-705a-11eb-8e30-af2e2f860ab5.png)

2021-02-17 19:30 UTC, FrankBishop commented
![Screenshot (208)](https://user-images.githubusercontent.com/75149451/108257386-8edb8300-7113-11eb-81e1-cf682985d9f1.png)

2021-02-17 19:31 UTC, codingcodymiller approved these changes

2021-02-17 19:32 UTC, merged