Javascript carousel - Frank Bishop
FrankBishop/c0121-code-solutions pull request #64
Opened 2021-02-18 05:50 UTC by FrankBishop

I had a lot of fun customizing this one
![Screenshot (209)](https://user-images.githubusercontent.com/75149451/108311535-0dfba600-716a-11eb-9df2-8349ec3b98ca.png)

2021-02-19 18:59 UTC, codingcodymiller requested changes
Great work so far, nice customization!! Please see my notes:

2021-02-19 18:59 UTC, codingcodymiller commented on javascript-carousel/main.js
> +  if (i < 5) {
Instead of using a magic hard-coded number here, you should make use of the `length` of the array that contains the values you want to loop over.

2021-02-19 18:59 UTC, codingcodymiller commented on javascript-carousel/main.js
> +  if (i <= 3) {
Instead of using a magic hard-coded number here, you should make use of the `length` of the array that contains the values you want to loop over.

2021-02-21 02:21 UTC, FrankBishop commented
Thanks for the feedback, I have implemented the requested fixes.

2021-02-21 21:22 UTC, thebearingedge requested changes

2021-02-21 21:22 UTC, thebearingedge commented on javascript-carousel/main.js
> +var dot5 = document.querySelector('.dot5');
Instead of grabbing every single dot individually, get a `NodeList`.

2021-02-21 21:22 UTC, thebearingedge commented on javascript-carousel/main.js
> +}
This is _a lot_ of repetition. Try using event delegation and loops.

2021-03-10 23:38 UTC, FrankBishop commented
I was able to greatly reduce the amount of code and have pushed the requested fixes.

2021-03-11 00:29 UTC, thebearingedge approved these changes
Much much better 👏

2021-03-11 01:13 UTC, merged