Array manipulation 3 - Frank Bishop
FrankBishop/c0121-code-solutions pull request #67
Opened 2021-02-19 23:17 UTC by FrankBishop

![Screenshot (218)](https://user-images.githubusercontent.com/75149451/108571685-917dda00-72c5-11eb-9877-ecdc10b9889a.png)

2021-02-21 21:09 UTC, thebearingedge approved these changes

2021-02-21 21:09 UTC, thebearingedge commented on array-manipulation-3/src/difference.js
> +  for (i = 0; i < second.length; i++) {
I noticed that you are consistently declaring your `i` or `key` outside of your loops. That's not a very common thing that people do. Instead you can declare your variable directly inside the initialization expression of the loop.

2021-02-21 21:09 UTC, thebearingedge commented on array-manipulation-3/src/flatten.js
> +    } else if (!Array.isArray(array[i])) {
You don't need to test if `!Arrary.isArray()`, since that is already established by the preceding `if` condition.

2021-02-21 21:09 UTC, thebearingedge commented on array-manipulation-3/src/intersection.js
> +  for (i = 0; i < first.length; i++) {
Declaring `i` like this is not "bad", but it is "weird".

2021-02-21 21:09 UTC, thebearingedge requested changes
Please see my notes

2021-02-21 23:55 UTC, merged

2021-03-01 00:21 UTC, FrankBishop commented
Since this initially showed as approved, I wasn't sure if I needed to make changes, but I went ahead and made them.

![Screenshot (243)](https://user-images.githubusercontent.com/75149451/109438910-e960c300-79e0-11eb-825b-308e60ddd606.png)

2021-03-16 01:44 UTC, thebearingedge commented
@FrankBishop Please make a small change to this branch and open a new pull request so i can mark it as approved.