String manipulation 3 - Frank Bishop
FrankBishop/c0121-code-solutions pull request #69
Opened 2021-02-21 02:14 UTC by FrankBishop

![Screenshot (220)](https://user-images.githubusercontent.com/75149451/108613492-72f00f80-73a7-11eb-8bd3-5e25ec933895.png)

2021-02-21 21:00 UTC, thebearingedge requested changes

2021-02-21 21:00 UTC, thebearingedge commented on string-manipulation-3/src/title-case.js
> +      newTitle = newTitle + ' ' + newWord;
You should rethink your approach a bit here. The rules provide you with a list of "short words" that you should put in your code somewhere. Your code needs to be able the handle _any_ title, not just the inputs provided.

2021-03-01 00:17 UTC, FrankBishop commented
Thanks for the feedback, I made the requested change.
![Screenshot (242)](https://user-images.githubusercontent.com/75149451/109438817-6b042100-79e0-11eb-9701-a3035fec1c89.png)

2021-03-01 16:58 UTC, thebearingedge requested changes
Ok, it's getting much better. Try handling hyphenated words and `:` before re-combining everything.

2021-03-01 16:58 UTC, thebearingedge commented on string-manipulation-3/src/title-case.js
> +    }
Instead of operating on the entire title, try working on the words in the title. If you leave them in an array, your code will be a lot more efficient.

2021-03-05 03:04 UTC, FrankBishop commented
It was a challenge, but I think I have it right now.

2021-03-05 03:16 UTC, thebearingedge approved these changes

2021-03-05 03:28 UTC, merged