Javascript bank - Frank Bishop
FrankBishop/c0121-code-solutions pull request #70
Opened 2021-02-21 19:12 UTC by FrankBishop

![Screenshot (221)](https://user-images.githubusercontent.com/75149451/108635701-99f52280-7435-11eb-8b46-15b8d0b036bc.png)

2021-02-21 21:18 UTC, thebearingedge requested changes

2021-02-21 21:18 UTC, thebearingedge commented on javascript-bank/account.js
> +    this.transactions.push(amount);
`this.transactions` should be an array of transaction objects, not a number.

2021-02-21 21:18 UTC, thebearingedge commented on javascript-bank/account.js
> +    this.transactions.push(-amount);
`this.transactions` should be an array of transaction objects, not a number.

2021-02-21 21:18 UTC, thebearingedge commented on javascript-bank/bank.js
> +    testAccount.transactions.push(balance);
the account's `deposit` method should be used to deposit the beginning balance.

2021-02-21 21:18 UTC, thebearingedge commented on javascript-bank/bank.js
> +  var j;
Please declare these in their respective loops.

2021-03-10 18:23 UTC, thebearingedge requested changes

2021-03-10 18:23 UTC, thebearingedge commented on javascript-bank/account.js
> +    this.transactions.push(deposit);
Instead of a plain object, create a `new Transaction()`, passing in the appropriate type and amount.

2021-03-10 18:23 UTC, thebearingedge commented on javascript-bank/account.js
> +    this.transactions.push(withdraw);
Instead of a plain object, create a `new Transaction()`, passing in the appropriate type and amount.

2021-03-10 18:23 UTC, thebearingedge commented on javascript-bank/account.js
> +      }
Here you can have one `if/else` that checks the `type` of transaction and adds or subtracts it from total as appropriate.

2021-03-10 20:51 UTC, FrankBishop commented
Thanks for the feedback, this is making some more sense now.
![Screenshot (298)](https://user-images.githubusercontent.com/75149451/110695950-56254b80-819f-11eb-83eb-26ee7c1ff504.png)

2021-03-10 21:02 UTC, thebearingedge requested changes
Great, much better. There is only one last weird part.

2021-03-10 21:02 UTC, thebearingedge commented on javascript-bank/bank.js
> +    testAccount.transactions.push(startBalance);
Here you are pushing `true` into the account's transactions. `deposit()` already pushed the transaction for you.

2021-03-11 06:25 UTC, FrankBishop commented
I think this fixed the issue with it pushing True into the array.
![Screenshot (303)](https://user-images.githubusercontent.com/75149451/110745054-8f85a780-81ef-11eb-88c9-ab481313e2e2.png)

2021-03-11 15:10 UTC, thebearingedge approved these changes

2021-03-11 18:00 UTC, merged