Working with collections - Frank Bishop
FrankBishop/c0121-code-solutions pull request #71
Opened 2021-02-27 22:14 UTC by FrankBishop

![Screenshot (241)](https://user-images.githubusercontent.com/75149451/109401870-21470800-7906-11eb-9334-8f37f49488fb.png)

2021-03-01 16:54 UTC, thebearingedge requested changes

2021-03-01 16:54 UTC, thebearingedge commented on working-with-collections/main.js
> +  {
Instead of writing your cards manually, try generating it with loops.

2021-03-05 01:43 UTC, FrankBishop commented
Thanks for the feedback, I updated it so the deck is created with loops.

2021-03-05 01:44 UTC, thebearingedge approved these changes

2021-03-05 01:44 UTC, merged