Express delete - Frank Bishop
FrankBishop/c0121-code-solutions pull request #92
Opened 2021-03-16 18:22 UTC by FrankBishop

![Screenshot (335)](https://user-images.githubusercontent.com/75149451/111360411-f2d96480-8649-11eb-95b5-a7be13ac29dd.png)
![Screenshot (336)](https://user-images.githubusercontent.com/75149451/111360421-f53bbe80-8649-11eb-875c-14168be1d17d.png)

2021-03-16 18:26 UTC, thebearingedge requested changes

2021-03-16 18:26 UTC, thebearingedge commented on express-delete/index.js
> +  }
Your array should only be declared in here where it's needed.

2021-03-16 18:26 UTC, thebearingedge commented on express-delete/index.js
> +  res.send(req.params);
You don't need to send the `req.params` back to the client.

2021-03-16 18:26 UTC, thebearingedge commented on express-delete/index.js
> +  grades.splice(req.params, 1);
Try using the `delete` operator on your `grades` object like you did in `node-notes-cli`.

2021-03-17 03:42 UTC, FrankBishop commented
Somehow other files got added to this when I pushed it and I can't find the correct one that was supposed to get pushed on GitHub.  We can look into it tomorrow.

Thanks

2021-03-17 16:13 UTC, thebearingedge approved these changes

2021-03-17 17:06 UTC, merged